{{- range $component := list "backend" "frontend" }}
{{- $comp := index $.Values $component }}
{{- if $comp.enabled }}
{{- if $comp.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $comp.ingress.name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ $.Values.issuer.name }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ $comp.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $comp.service.name }}
                port:
                  name: {{ $comp.service.ports.name }}
  tls:
    - hosts:
        - {{ $comp.ingress.host }}
      secretName: {{ $comp.ingress.secretName }}
---
{{- end }}
{{- end }}
{{- end }}