{{- if .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.frontend.ingress.name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.issuer.name }}
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.frontend.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.service.name }}
            port:
              name: {{ .Values.frontend.service.ports.name }}
  tls:
  - hosts:
    - {{ .Values.frontend.ingress.host }}
    secretName: {{ .Values.frontend.ingress.secretName }}
{{- end }}
---
{{- if .Values.backend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.backend.ingress.name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.issuer.name }}
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.backend.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.service.name }}
            port:
              name: {{ .Values.backend.service.ports.name }}
  tls:
  - hosts:
    - {{ .Values.backend.ingress.host }}
    secretName: {{ .Values.backend.ingress.secretName }}
{{- end }}