{{- range $component := list "backend" "frontend" }}
{{- $comp := index $.Values $component }}
{{- if $comp.enabled }}
{{- if $comp.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" $component }}
data:
{{- range $key, $val := $comp.secret.values }}
  {{ $key }}: {{ $val }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}