---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pharmacy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: pharmacy
spec:
  project: default
  source:
    repoURL: 'https://github.com/BohdanHavran/Diploma.git'
    path: app
    targetRevision: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pharmacy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true