resources:
  - ./app

namespace: pharmacy

helmGlobals:
  chartHome: ./helm

helmCharts:
  - releaseName: pharmacy
    namespace: pharmacy
    name: pharmacy-app
    version: 0.1.0
    includeCRDs: false
    valuesFile: values.yml

  # - name: flowable
  #   releaseName: flowable
  #   repo: https://flowable.github.io/helm/
  #   namespace: business-processes
  #   version: 6.8.0
  #   valuesFile: flowable-values.yml