backend:
  enabled: true

  deployment:
    enabled: true
    name: backend
    replicas: 1
    containers:
      image: registry.digitalocean.com/pharmacy/backend:0c359fe
      ports:
        containerPort: 5000
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    livenessProbe:
      httpGet:
        path: /api/health
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /api/health
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
  secret:
    JWT_SECRET_KEY: ZWJlMjFkMmU5YWZmNzQ5ZTY1M2FkYzcxNTM3MTg2YTZkZWQ5MDljNDNjNzI5NDhjZmFmMmY2YzZjY2RhZGZhNQ==
    JWT_ACCESS_TOKEN_EXPIRES: MTgwMA==
    JWT_REFRESH_TOKEN_EXPIRES: ODY0MDA=
    DB_HOST: cHJpdmF0ZS1waGFybWFjeS1jbHVzdGVyLWRvLXVzZXItMjI0MzI2NDMtMC5kLmRiLm9uZGlnaXRhbG9jZWFuLmNvbQ==
    DB_PORT: MjUwNjA=
    DB_USER: UGhhcm1hY3k=
    DB_PASSWORD: QVZOU19YbnBySDhCWE1vNUhUVHhJTUhr
    DB_NAME: UGhhcm1hY3k=
    DO_SPACES_KEY: RE8wMEM4S0dMWU4yQ1U3VVBXOUs=
    DO_SPACES_SECRET: REhxTmUrWE5VM0RERVpwSEJPWlROV2FPTHJadVo2RU5FNlhmRnlDMWQvaw==
    DO_SPACES_REGION: ZnJhMQ==
    DO_SPACES_ENDPOINT: aHR0cHM6Ly9mcmExLmRpZ2l0YWxvY2VhbnNwYWNlcy5jb20=
    DO_SPACES_BUCKET: cGhhcm1hY3ktYnVja2V0
  hpa:
    enabled: true
    metadata:
      serverAddress: http://monitoring-stack-kube-prom-prometheus.monitoring-stack:9090
      metricName: container_cpu_usage
      query: sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{namespace="{{ .Release.Namespace }}", pod=~"{{ $comp.deployment.name }}", container!=""}) by (container)
      threshold: '0.075'
      ignoreNullValues: false
    pollingInterval: 5
    minReplicas: 1
    maxReplicas: 5
  service:
    enabled: true
    name: api-service
    ports:
      name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  ingress:
    enabled: true
    name: api-server-ingress
    host: api.diplom.dns.army
    email: diploma@gmail.com
    secretName: api-server-tls

frontend:
  enabled: true

  deployment:
    enabled: true
    name: frontend
    replicas: 1
    containers:
      image: registry.digitalocean.com/pharmacy/frontend:9f6faea
      ports:
        containerPort: 80
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
  hpa:
    enabled: true
    metadata:
      serverAddress: http://monitoring-stack-kube-prom-prometheus.monitoring-stack:9090
      metricName: container_cpu_usage
      query: sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{namespace="{{ .Release.Namespace }}", pod=~"{{ $comp.deployment.name }}", container!=""}) by (container)
      threshold: '0.075'
      ignoreNullValues: false
    pollingInterval: 5
    minReplicas: 1
    maxReplicas: 5
  service:
    enabled: true
    name: app-service
    ports:
      name: http
      protocol: TCP
      port: 80
      targetPort: 80
  ingress:
    enabled: true
    name: app-server-ingress
    host: diplom.dns.army
    email: diploma@gmail.com
    secretName: app-server-tls
  
issuer:
  create: true
  name: letsencrypt-pharmacy
  email: diploma@gmail.com
  secretName: letsencrypt-pharmacy