backend:
  enabled: true

  deployment:
    enabled: true
    name: backend
    replicas: 1
    containers:
      image: registry.digitalocean.com/pharmacy/backend:ec83f8e
      ports:
        containerPort: 5000
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  hpa:
    enabled: true
    metadata:
      serverAddress: http://monitoring-stack-kube-prom-prometheus.monitoring-stack:9090
      metricName: container_cpu_usage
      query: sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{namespace="{{ .Release.Namespace }}", pod=~"{{ $comp.deployment.name }}", container!=""}) by (container)
      threshold: 
      ignoreNullValues: false
    pollingInterval: 5
    minReplicas: 1
    maxReplicas: 5

  service:
    enabled: true
    name: api-service
    ports:
      name: http
      protocol: TCP
      port: 80
      targetPort: 5000

  ingress:
    enabled: true
    name: api-server-ingress
    host: api.diplom.dns.army
    email: diploma@gmail.com
    secretName: api-server-tls

frontend:
  enabled: true

  deployment:
    enabled: true
    name: frontend
    replicas: 1
    containers:
      image: registry.digitalocean.com/pharmacy/frontend:7bc9d05
      ports:
        containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  hpa:
    enabled: true
    metadata:
      serverAddress: http://monitoring-stack-kube-prom-prometheus.monitoring-stack:9090
      metricName: container_cpu_usage
      query: sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{namespace="{{ .Release.Namespace }}", pod=~"{{ $comp.deployment.name }}", container!=""}) by (container)
      threshold: 
      ignoreNullValues: false
    pollingInterval: 5
    minReplicas: 1
    maxReplicas: 5

  service:
    enabled: true
    name: app-service
    ports:
      name: http
      protocol: TCP
      port: 80
      targetPort: 80

  ingress:
    enabled: true
    name: app-server-ingress
    host: diplom.dns.army
    email: diploma@gmail.com
    secretName: app-server-tls
  
issuer:
  create: true
  name: letsencrypt-pharmacy
  email: diploma@gmail.com
  secretName: letsencrypt-pharmacy