apiVersion: v1
kind: ConfigMap
data:
  policy.csv: |
    p, role:github-actions, applications, get, */*, allow
    p, role:github-actions, applications, sync, */*, allow
    g, github-actions, role:github-actions
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-rbac-cm","namespace":"argocd"}}
  creationTimestamp: "2025-05-17T17:58:47Z"
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "389704"
  uid: 811e835b-c639-4b91-884d-a7602f479c8c
